framework:
  http_client:
    scoped_clients:
      gotenberg.client:
        base_uri: '%env(GOTENBERG_DSN)%'
        # or you can leverage this endpoint for fast testing without Docker
        # base_uri: 'https://demo.gotenberg.dev'