sensiolabs_gotenberg:
  assets_directory: 'public'
  http_client: 'gotenberg.client'
  webhook:
    webhook_pdf_config:
      success:
        url: "http://host.docker.internal:8500/gotenberg-bundle-webhook-success"
      error:
        url: "http://host.docker.internal:8500/gotenberg-bundle-webhook-error"
