sensiolabs_gotenberg:
  assets_directory: 'public'
  http_client: 'gotenberg.client'
  webhook:
    webhook_pdf_config:
      success:
        url: "http://host.docker.internal:8500/gotenberg-symfony-bundle-webhook-success-pdf"
      error:
        url: "http://host.docker.internal:8500/gotenberg-symfony-bundle-webhook-error-pdf"
#  default_options:
#      webhook: 'webhook_pdf_config'
