services:

  mysql:
    image: mysql:8
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - gotenberg-data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: gotenberg-nginx
    depends_on:
      - php
    volumes:
      - ../:/srv
      - ./nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - gotenberg-network

  php:
    build:
      context: ./php
      dockerfile: ./Dockerfile
    container_name: gotenberg-php
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      XDEBUG_MODE: "debug"
      XDEBUG_CONFIG: >-
        idekey=PHPSTORM
        client_host=host.docker.internal
        log_level=0
        output_dir=/srv/api/tests/Reports/profiles
      PHP_IDE_CONFIG: serverName=gotenberg-docker
    volumes:
      - ../:/srv
      - ./php/php.ini:/usr/local/etc/php/conf.d/000-php.ini
      - ./php/zz-php-fpm.conf:/usr/local/etc/php-fpm.d/zz-php-fpm.conf
    depends_on:
      - mysql
    networks:
      - gotenberg-network

  gotenberg:
    image: gotenberg/gotenberg:8
    container_name: gotenberg-gotenberg
    depends_on:
      - php
    networks:
      - gotenberg-network
    ports:
      - '3000:3000'

volumes:
  gotenberg-data: {}

networks:
  gotenberg-network:
    driver: bridge
